server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/db_appoiment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mysqluser
    password: secret
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  #mostar por consola los datos de los queries
  jpa:
    show-sql: true
    #autogenera las tablas
    hibernate:
      ddl-auto: create-drop
    #dialecto de las base de datos
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect