spring:
  datasource:
    url: jdbc:mysql://localhost:13306/db_appoiment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mysqluser
    password: secret


  #mostar por consola los datos de los queries
  jpa:
    show-sql: true
    #autogenera las tablas
    hibernate:
      ddl-auto: create-drop
    #dialecto de las base de datos
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect