server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FranciscoFavelaNajera/Microservicios-Appoiments
          search-paths: config-data
            username: ${GIT_USER}
            password: ${GIT_PASSWORD}
  application:
    name: config-service